import { User, Destination, Experience, TourEvent, Review, Post, Badge, Booking, ChatRoom, ChatMessage, Itinerary, Notification, UserPoints, UserStreak, UserBadge } from '@/types';

// ===== USERS =====
export const mockUsers: User[] = [
  {
    id: 'u1', email: 'rahul@gmail.com', role: 'tourist', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face', phone: '+91-9876543210', emailVerified: true, createdAt: '2024-06-01',
    profile: { firstName: 'Rahul', lastName: 'Sharma', bio: 'Adventure seeker and food lover. Love exploring hidden gems across India.', nationality: 'Indian', languages: ['English', 'Hindi', 'Marathi'], interests: ['adventure', 'food', 'heritage'], location: 'Mumbai, Maharashtra', latitude: 19.076, longitude: 72.8777 },
  },
  {
    id: 'u2', email: 'priya@gmail.com', role: 'tourist', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face', phone: '+91-9876543211', emailVerified: true, createdAt: '2024-05-15',
    profile: { firstName: 'Priya', lastName: 'Patel', bio: 'Solo traveler exploring culture and heritage across South Asia.', nationality: 'Indian', languages: ['English', 'Hindi', 'Gujarati'], interests: ['cultural', 'heritage', 'eco'], location: 'Ahmedabad, Gujarat', latitude: 23.0225, longitude: 72.5714 },
  },
  {
    id: 'g1', email: 'arjun.guide@gmail.com', role: 'guide', avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face', phone: '+91-9876543212', emailVerified: true, createdAt: '2024-03-10',
    profile: { firstName: 'Arjun', lastName: 'Reddy', bio: 'History student at University of Hyderabad. Passionate about showing tourists the real Hyderabad beyond the usual tourist spots.', nationality: 'Indian', languages: ['English', 'Hindi', 'Telugu', 'Urdu'], interests: ['heritage', 'food', 'cultural'], location: 'Hyderabad, Telangana', latitude: 17.385, longitude: 78.4867 },
    guideProfile: { id: 'gp1', userId: 'g1', verified: true, university: 'University of Hyderabad', studentId: 'UH2023456', yearsOfExperience: 3, specializations: ['heritage', 'food', 'cultural'], certifications: [{ name: 'Certified Heritage Guide', issuer: 'Indian Heritage Society', year: 2023 }], pricePerHour: 500, pricePerDay: 3000, availableDays: ['Saturday', 'Sunday', 'Monday'], maxGroupSize: 8, totalEarnings: 245000, avgRating: 4.8, totalReviews: 127, totalBookings: 189 },
  },
  {
    id: 'g2', email: 'sneha.guide@gmail.com', role: 'guide', avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face', phone: '+91-9876543213', emailVerified: true, createdAt: '2024-02-20',
    profile: { firstName: 'Sneha', lastName: 'Nair', bio: 'Environmental Science student at IISc Bangalore. Specializing in eco-tourism and Western Ghats biodiversity tours.', nationality: 'Indian', languages: ['English', 'Hindi', 'Kannada', 'Malayalam'], interests: ['eco', 'adventure', 'village'], location: 'Bengaluru, Karnataka', latitude: 12.9716, longitude: 77.5946 },
    guideProfile: { id: 'gp2', userId: 'g2', verified: true, university: 'IISc Bangalore', studentId: 'IISC2023789', yearsOfExperience: 2, specializations: ['eco', 'adventure', 'village'], certifications: [{ name: 'Wildlife Guide Certification', issuer: 'Karnataka Forest Dept', year: 2023 }, { name: 'First Aid Certified', issuer: 'Red Cross India', year: 2024 }], pricePerHour: 600, pricePerDay: 3500, availableDays: ['Friday', 'Saturday', 'Sunday'], maxGroupSize: 6, totalEarnings: 178000, avgRating: 4.9, totalReviews: 89, totalBookings: 134 },
  },
  {
    id: 'g3', email: 'vikram.guide@gmail.com', role: 'guide', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face', phone: '+91-9876543214', emailVerified: true, createdAt: '2024-04-05',
    profile: { firstName: 'Vikram', lastName: 'Singh', bio: 'Architecture student at SPA Delhi. Expert in Mughal architecture and Delhi\'s hidden historical gems.', nationality: 'Indian', languages: ['English', 'Hindi', 'Punjabi'], interests: ['heritage', 'cultural', 'food'], location: 'New Delhi, Delhi', latitude: 28.6139, longitude: 77.209 },
    guideProfile: { id: 'gp3', userId: 'g3', verified: true, university: 'School of Planning & Architecture, Delhi', studentId: 'SPA2024123', yearsOfExperience: 1, specializations: ['heritage', 'cultural'], certifications: [{ name: 'Archaeological Survey Guide', issuer: 'ASI India', year: 2024 }], pricePerHour: 400, pricePerDay: 2500, availableDays: ['Saturday', 'Sunday'], maxGroupSize: 10, totalEarnings: 89000, avgRating: 4.6, totalReviews: 56, totalBookings: 78 },
  },
  {
    id: 'g4', email: 'meera.guide@gmail.com', role: 'guide', avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face', phone: '+91-9876543215', emailVerified: true, createdAt: '2024-01-15',
    profile: { firstName: 'Meera', lastName: 'Krishnan', bio: 'Culinary Arts student at Welcomgroup Graduate School. I turn every tour into a food adventure!', nationality: 'Indian', languages: ['English', 'Hindi', 'Tamil', 'French'], interests: ['food', 'cultural', 'village'], location: 'Chennai, Tamil Nadu', latitude: 13.0827, longitude: 80.2707 },
    guideProfile: { id: 'gp4', userId: 'g4', verified: true, university: 'Welcomgroup Graduate School of Hotel Administration', studentId: 'WG2023567', yearsOfExperience: 2, specializations: ['food', 'cultural', 'village'], certifications: [{ name: 'Food Safety Certification', issuer: 'FSSAI', year: 2023 }], pricePerHour: 550, pricePerDay: 3200, availableDays: ['Wednesday', 'Saturday', 'Sunday'], maxGroupSize: 8, totalEarnings: 156000, avgRating: 4.7, totalReviews: 73, totalBookings: 112 },
  },
  {
    id: 'g5', email: 'ananya.guide@gmail.com', role: 'guide', avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face', phone: '+91-9876543216', emailVerified: true, createdAt: '2024-05-01',
    profile: { firstName: 'Ananya', lastName: 'Desai', bio: 'Marine Biology student at Goa University. Expert in beach ecology, water sports guidance, and Goan heritage walks.', nationality: 'Indian', languages: ['English', 'Hindi', 'Konkani', 'Portuguese'], interests: ['eco', 'adventure', 'cultural'], location: 'Panaji, Goa', latitude: 15.4909, longitude: 73.8278 },
    guideProfile: { id: 'gp5', userId: 'g5', verified: true, university: 'Goa University', studentId: 'GU2024890', yearsOfExperience: 1, specializations: ['eco', 'adventure', 'cultural'], certifications: [{ name: 'PADI Open Water Diver', issuer: 'PADI', year: 2024 }], pricePerHour: 450, pricePerDay: 2800, availableDays: ['Thursday', 'Friday', 'Saturday', 'Sunday'], maxGroupSize: 6, totalEarnings: 67000, avgRating: 4.5, totalReviews: 34, totalBookings: 45 },
  },
  {
    id: 'a1', email: 'admin@tourmate.ai', role: 'admin', avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop&crop=face', phone: '+91-9876543200', emailVerified: true, createdAt: '2024-01-01',
    profile: { firstName: 'Admin', lastName: 'TourMate', bio: 'Platform Administrator', nationality: 'Indian', languages: ['English', 'Hindi'], interests: [], location: 'Bengaluru, Karnataka' },
  },
];

// ===== DESTINATIONS =====
export const mockDestinations: Destination[] = [
  {
    id: 'd1', name: 'Hampi Ruins', slug: 'hampi-ruins', description: 'The magnificent ruins of the Vijayanagara Empire, a UNESCO World Heritage Site spread across boulder-strewn landscapes. Explore ancient temples, royal enclosures, and sacred complexes that tell tales of one of the largest cities in the medieval world. The surreal landscape of giant boulders and palm trees makes it a photographer\'s paradise.', shortDesc: 'UNESCO World Heritage ruins of the Vijayanagara Empire', coverImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800&h=600&fit=crop'], latitude: 15.335, longitude: 76.46, address: 'Hampi, Vijayanagara District', city: 'Hampi', state: 'Karnataka', country: 'India', bestSeason: 'October - February', avgBudget: 3000, difficulty: 'Easy', tags: ['UNESCO', 'ruins', 'photography', 'history'], categories: ['heritage', 'cultural', 'hidden_gem'], featured: true, published: true, avgRating: 4.8, totalReviews: 2341, viewCount: 45000, createdAt: '2024-01-15',
  },
  {
    id: 'd2', name: 'Coorg Coffee Trails', slug: 'coorg-coffee-trails', description: 'Walk through lush coffee plantations in the Scotland of India. Experience the entire coffee-making process from bean to cup while surrounded by misty hills and exotic wildlife. The region offers stunning waterfalls, spice gardens, and a unique Kodava culture.', shortDesc: 'Walk through lush coffee plantations in the Scotland of India', coverImage: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800&h=600&fit=crop'], latitude: 12.3375, longitude: 75.8069, address: 'Madikeri, Kodagu District', city: 'Coorg', state: 'Karnataka', country: 'India', bestSeason: 'October - March', avgBudget: 5000, difficulty: 'Easy', tags: ['coffee', 'nature', 'plantation', 'monsoon'], categories: ['eco', 'village', 'hidden_gem'], featured: true, published: true, avgRating: 4.7, totalReviews: 1890, viewCount: 38000, createdAt: '2024-02-10',
  },
  {
    id: 'd3', name: 'Chettinad Heritage Walk', slug: 'chettinad-heritage-walk', description: 'Discover the magnificent mansions of the Chettinad region in Tamil Nadu. These palatial homes, built by wealthy Nattukotai Chettiars, feature Italian marble floors, Burmese teak pillars, and Belgian chandeliers. Experience authentic Chettinad cuisine known for its complex spice blends.', shortDesc: 'Magnificent mansions and legendary cuisine of Tamil Nadu', coverImage: '/images/chettinad_heritage.png', images: ['/images/chettinad_heritage.png'], latitude: 10.1632, longitude: 78.9924, address: 'Karaikudi, Sivaganga District', city: 'Chettinad', state: 'Tamil Nadu', country: 'India', bestSeason: 'November - March', avgBudget: 4000, difficulty: 'Easy', tags: ['heritage', 'mansions', 'cuisine', 'architecture'], categories: ['heritage', 'food', 'cultural', 'hidden_gem'], featured: true, published: true, avgRating: 4.6, totalReviews: 876, viewCount: 22000, createdAt: '2024-02-20',
  },
  {
    id: 'd4', name: 'Spiti Valley', slug: 'spiti-valley', description: 'The remote cold desert mountain valley in the Himalayas. Home to ancient Buddhist monasteries perched on cliff edges, crystal clear rivers, and star-studded night skies. One of the least populated regions of India offering an otherworldly experience.', shortDesc: 'Remote Himalayan cold desert with ancient monasteries', coverImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop'], latitude: 32.2464, longitude: 78.0349, address: 'Kaza, Lahaul and Spiti', city: 'Spiti', state: 'Himachal Pradesh', country: 'India', bestSeason: 'June - September', avgBudget: 15000, difficulty: 'Challenging', tags: ['mountains', 'monastery', 'adventure', 'photography'], categories: ['adventure', 'hidden_gem', 'cultural', 'religious'], featured: true, published: true, avgRating: 4.9, totalReviews: 1567, viewCount: 52000, createdAt: '2024-03-01',
  },
  {
    id: 'd5', name: 'Majuli Island', slug: 'majuli-island', description: 'The world\'s largest river island on the Brahmaputra in Assam. A vibrant hub of Assamese Neo-Vaishnavite culture with ancient Satras (monasteries), mask-making traditions, and a unique way of life that\'s slowly being shaped by the river. A hidden gem for cultural explorers.', shortDesc: 'World\'s largest river island with unique Assamese culture', coverImage: '/images/majuli_island.png', images: ['/images/majuli_island.png'], latitude: 26.95, longitude: 94.1672, address: 'Majuli District', city: 'Majuli', state: 'Assam', country: 'India', bestSeason: 'October - March', avgBudget: 4000, difficulty: 'Moderate', tags: ['island', 'culture', 'monastery', 'tribal'], categories: ['hidden_gem', 'cultural', 'village', 'eco'], featured: false, published: true, avgRating: 4.5, totalReviews: 445, viewCount: 12000, createdAt: '2024-03-15',
  },
  {
    id: 'd6', name: 'Old Delhi Food Trail', slug: 'old-delhi-food-trail', description: 'Navigate the narrow, bustling lanes of Old Delhi for the ultimate street food experience. From the legendary parathas of Chandni Chowk to the kebabs of Jama Masjid area, every corner offers a new flavor explosion. This 400-year-old food heritage is a must for every foodie.', shortDesc: 'Legendary street food trail through the heart of Old Delhi', coverImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=600&fit=crop'], latitude: 28.6562, longitude: 77.2307, address: 'Chandni Chowk, Old Delhi', city: 'New Delhi', state: 'Delhi', country: 'India', bestSeason: 'October - March', avgBudget: 1500, difficulty: 'Easy', tags: ['street food', 'Delhi', 'culinary', 'walking tour'], categories: ['food', 'cultural', 'heritage'], featured: true, published: true, avgRating: 4.7, totalReviews: 3456, viewCount: 67000, createdAt: '2024-01-05',
  },
  {
    id: 'd7', name: 'Dzukou Valley', slug: 'dzukou-valley', description: 'The valley of flowers of the Northeast, located at the border of Nagaland and Manipur. A pristine carpet of wildflowers, bamboo groves, and lilies spread across rolling hills at 2,438m altitude. The trek offers stunning views and a surreal experience away from all civilization.', shortDesc: 'The hidden valley of flowers in Northeast India', coverImage: '/images/dzukou_valley.png', images: ['/images/dzukou_valley.png'], latitude: 25.5667, longitude: 93.95, address: 'Dzukou Valley, Kohima District', city: 'Kohima', state: 'Nagaland', country: 'India', bestSeason: 'June - September', avgBudget: 5000, difficulty: 'Challenging', tags: ['trekking', 'flowers', 'Northeast', 'camping'], categories: ['adventure', 'hidden_gem', 'eco'], featured: false, published: true, avgRating: 4.8, totalReviews: 334, viewCount: 8900, createdAt: '2024-04-10',
  },
  {
    id: 'd8', name: 'Pondicherry French Quarter', slug: 'pondicherry-french-quarter', description: 'Stroll through pastel-colored streets of the former French colony. The White Town area features colonial architecture, seaside promenades, charming cafes, and art galleries. A perfect blend of French elegance and Tamil culture creating a unique Indo-French ambiance.', shortDesc: 'Indo-French colonial charm with pastel streets and cafes', coverImage: '/images/destinations/pondicherry.png', images: ['/images/destinations/pondicherry.png'], latitude: 11.9416, longitude: 79.8083, address: 'White Town, Puducherry', city: 'Pondicherry', state: 'Puducherry', country: 'India', bestSeason: 'October - March', avgBudget: 4500, difficulty: 'Easy', tags: ['French', 'colonial', 'cafes', 'beach', 'architecture'], categories: ['cultural', 'heritage', 'food'], featured: true, published: true, avgRating: 4.5, totalReviews: 2100, viewCount: 41000, createdAt: '2024-02-01',
  },
  {
    id: 'd9', name: 'Living Root Bridges', slug: 'living-root-bridges', description: 'Marvel at the incredible living architecture of Meghalaya — bridges grown from the roots of rubber fig trees by the Khasi and Jaintia tribes over centuries. The double-decker root bridge at Nongriat is a UNESCO World Heritage nominee and one of India\'s most remarkable engineering feats.', shortDesc: 'Ancient living architecture grown from tree roots in Meghalaya', coverImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=600&fit=crop'], latitude: 25.2876, longitude: 91.5822, address: 'Nongriat Village, East Khasi Hills', city: 'Cherrapunji', state: 'Meghalaya', country: 'India', bestSeason: 'October - May', avgBudget: 6000, difficulty: 'Challenging', tags: ['trek', 'nature', 'tribal', 'unique', 'Northeast'], categories: ['hidden_gem', 'eco', 'adventure', 'village'], featured: true, published: true, avgRating: 4.9, totalReviews: 987, viewCount: 29000, createdAt: '2024-03-20',
  },
  {
    id: 'd10', name: 'Rann of Kutch', slug: 'rann-of-kutch', description: 'Experience the surreal white desert of Gujarat that stretches endlessly under full moonlight. During the Rann Utsav festival, the area comes alive with folk music, dance, handicrafts, and cultural performances. The salt marshes create an otherworldly landscape unique to India.', shortDesc: 'Surreal white salt desert under the moonlight in Gujarat', coverImage: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800&h=600&fit=crop'], latitude: 23.7337, longitude: 69.8597, address: 'Dhordo, Kutch District', city: 'Kutch', state: 'Gujarat', country: 'India', bestSeason: 'November - February', avgBudget: 8000, difficulty: 'Easy', tags: ['desert', 'festival', 'moonlight', 'handicrafts'], categories: ['cultural', 'hidden_gem', 'family', 'village'], featured: true, published: true, avgRating: 4.6, totalReviews: 1876, viewCount: 35000, createdAt: '2024-01-25',
  },
  {
    id: 'd11', name: 'Gandikota Canyon', slug: 'gandikota-canyon', description: 'India\'s Grand Canyon — a breathtaking gorge carved by the Pennar River through Erramala hills. This hidden gem in Andhra Pradesh features dramatic cliff faces, a 13th-century fort, and ancient Jain and Hindu temples. Far less crowded than any major tourist destination.', shortDesc: 'India\'s hidden Grand Canyon with ancient fort ruins', coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'], latitude: 15.1757, longitude: 78.2842, address: 'Gandikota, Kadapa District', city: 'Gandikota', state: 'Andhra Pradesh', country: 'India', bestSeason: 'October - February', avgBudget: 3500, difficulty: 'Moderate', tags: ['canyon', 'fort', 'camping', 'gorge'], categories: ['hidden_gem', 'adventure', 'heritage'], featured: false, published: true, avgRating: 4.7, totalReviews: 567, viewCount: 15000, createdAt: '2024-04-15',
  },
  {
    id: 'd12', name: 'Varanasi Ghats', slug: 'varanasi-ghats', description: 'The spiritual heart of India. Experience the mesmerizing Ganga Aarti ceremony at Dashashwamedh Ghat, explore 84 ancient ghats along the river, and witness the cycle of life and death in the world\'s oldest continuously inhabited city. A profound cultural and spiritual experience.', shortDesc: 'Spiritual heart of India with ancient ghats and ceremonies', coverImage: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&h=600&fit=crop'], latitude: 25.3176, longitude: 83.0064, address: 'Dashashwamedh Ghat, Varanasi', city: 'Varanasi', state: 'Uttar Pradesh', country: 'India', bestSeason: 'October - March', avgBudget: 3000, difficulty: 'Easy', tags: ['spiritual', 'Ganga', 'ceremony', 'ancient city'], categories: ['religious', 'cultural', 'heritage'], featured: true, published: true, avgRating: 4.7, totalReviews: 4532, viewCount: 89000, createdAt: '2024-01-10',
  },
  {
    id: 'd13', name: 'Araku Valley', slug: 'araku-valley', description: 'A pristine hill station in the Visakhapatnam district, famous for its lush coffee plantations, tribal culture, and the spectacular Galikonda viewpoint. Take the scenic Vistadome train ride through 58 tunnels and 84 bridges to reach this serene getaway untouched by commercialization.', shortDesc: 'Pristine hill station known for coffee plantations and tribal culture', coverImage: '/images/araku_valley.png', images: ['/images/araku_valley.png'], latitude: 18.3273, longitude: 82.8775, address: 'Araku Valley, Alluri Sitharama Raju District', city: 'Visakhapatnam', state: 'Andhra Pradesh', country: 'India', bestSeason: 'September - February', avgBudget: 3500, difficulty: 'Easy', tags: ['hill station', 'coffee', 'train ride', 'tribal'], categories: ['village', 'eco', 'family', 'hidden_gem'], featured: true, published: true, avgRating: 4.8, totalReviews: 2150, viewCount: 32000, createdAt: '2024-06-18',
  },
  {
    id: 'd14', name: 'Borra Caves', slug: 'borra-caves', description: 'One of the largest and deepest cave systems in India, located in the Ananthagiri hills of the Eastern Ghats. Discovered by William King George of the Geological Survey of India in 1881, these million-year-old limestone caves feature breathtaking stalactite and stalagmite formations illuminated by colorful lights.', shortDesc: 'Million-year-old limestone caves with spectacular formations', coverImage: '/images/borra_caves.png', images: ['/images/borra_caves.png'], latitude: 18.2808, longitude: 83.0396, address: 'Ananthagiri Hills, Araku Valley', city: 'Visakhapatnam', state: 'Andhra Pradesh', country: 'India', bestSeason: 'November - March', avgBudget: 1500, difficulty: 'Moderate', tags: ['caves', 'geology', 'nature', 'photography'], categories: ['adventure', 'hidden_gem', 'eco'], featured: false, published: true, avgRating: 4.6, totalReviews: 1890, viewCount: 25000, createdAt: '2024-06-18',
  },
  {
    id: 'd15', name: 'Lambasingi', slug: 'lambasingi', description: 'Often referred to as the "Kashmir of Andhra Pradesh," Lambasingi is a tiny tribal village in the Chintapalli region known for being the only place in South India that occasionally experiences snowfall. Wake up to freezing temperatures, dense mist, and spectacular sunrises over rolling hills.', shortDesc: 'The Kashmir of Andhra Pradesh known for misty mornings and zero-degree winters', coverImage: '/images/lambasingi.png', images: ['/images/lambasingi.png'], latitude: 17.8166, longitude: 82.4962, address: 'Chintapalli Mandal, ASR District', city: 'Visakhapatnam', state: 'Andhra Pradesh', country: 'India', bestSeason: 'December - January', avgBudget: 2500, difficulty: 'Moderate', tags: ['hill station', 'winter', 'mist', 'camping'], categories: ['hidden_gem', 'adventure', 'village'], featured: true, published: true, avgRating: 4.7, totalReviews: 1240, viewCount: 41000, createdAt: '2024-06-18',
  },
  {
    id: 'd16', name: 'Belum Caves', slug: 'belum-caves', description: 'The second largest and longest cave system in the Indian subcontinent. Known for its unique speleothems, such as stalactite and stalagmite formations, these caves have long passages, spacious chambers, fresh water galleries, and siphons. An underground adventure unlike any other.', shortDesc: 'The second longest cave system in the Indian subcontinent', coverImage: '/images/belum_caves.png', images: ['/images/belum_caves.png'], latitude: 15.1026, longitude: 78.1116, address: 'Belum Village, Kurnool District', city: 'Kurnool', state: 'Andhra Pradesh', country: 'India', bestSeason: 'August - December', avgBudget: 1200, difficulty: 'Moderate', tags: ['caves', 'geology', 'exploration', 'underground'], categories: ['hidden_gem', 'adventure', 'eco'], featured: true, published: true, avgRating: 4.8, totalReviews: 950, viewCount: 20000, createdAt: '2024-06-19',
  },
  {
    id: 'd17', name: 'Lepakshi Temple', slug: 'lepakshi-temple', description: 'A marvel of the Vijayanagara architectural style, famous for its hanging pillar, spectacular mural paintings, and the colossal monolithic Nandi. Experience the rich mythology, magnificent stone carvings, and unexplainable architectural mysteries.', shortDesc: 'Architectural marvel famous for its hanging pillar and monolithic Nandi', coverImage: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&h=600&fit=crop'], latitude: 13.8037, longitude: 77.6050, address: 'Lepakshi, Sri Sathya Sai District', city: 'Anantapur', state: 'Andhra Pradesh', country: 'India', bestSeason: 'October - March', avgBudget: 1500, difficulty: 'Easy', tags: ['heritage', 'temple', 'architecture', 'mythology'], categories: ['heritage', 'cultural', 'religious'], featured: true, published: true, avgRating: 4.9, totalReviews: 1420, viewCount: 30000, createdAt: '2024-06-19',
  },
  {
    id: 'd18', name: 'Maredumilli', slug: 'maredumilli', description: 'An eco-tourism paradise nestled in the dense forests of the Eastern Ghats. Known for its pristine waterfalls (Jalatarangini, Swarnadhara), thick bamboo bushes, tribal culture, and the famous bamboo chicken. A perfect serene getaway for nature lovers.', shortDesc: 'Pristine eco-tourism spot famous for waterfalls and bamboo chicken', coverImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=600&fit=crop'], latitude: 17.6046, longitude: 81.7042, address: 'Maredumilli, Alluri Sitharama Raju District', city: 'Rajahmundry', state: 'Andhra Pradesh', country: 'India', bestSeason: 'September - January', avgBudget: 3000, difficulty: 'Moderate', tags: ['eco', 'waterfalls', 'tribal', 'forest'], categories: ['eco', 'village', 'hidden_gem'], featured: false, published: true, avgRating: 4.6, totalReviews: 890, viewCount: 18000, createdAt: '2024-06-19',
  },
  {
    id: 'd19', name: 'Papikondalu', slug: 'papikondalu', description: 'A breathtakingly beautiful mountain range running along the Godavari River. The scenic boat cruise through the narrow gorge flanked by lush green hills on both sides is an unforgettable experience. Experience the serene river flow and remote tribal villages.', shortDesc: 'Scenic mountain range famous for Godavari river cruises', coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop'], latitude: 17.3916, longitude: 81.5647, address: 'Papikondalu, Godavari Districts', city: 'Rajahmundry', state: 'Andhra Pradesh', country: 'India', bestSeason: 'October - March', avgBudget: 4000, difficulty: 'Easy', tags: ['river', 'cruise', 'mountains', 'nature'], categories: ['adventure', 'eco', 'hidden_gem'], featured: true, published: true, avgRating: 4.7, totalReviews: 2100, viewCount: 45000, createdAt: '2024-06-19',
  },
  {
    id: 'd20', name: 'Coringa Wildlife Sanctuary', slug: 'coringa-wildlife-sanctuary', description: 'The second largest stretch of mangrove forests in India. A paradise for bird watchers and eco-tourists. Navigate through the dense mangroves on a boat and spot a variety of exotic bird species, fishing cats, and estuarine crocodiles.', shortDesc: 'India\'s second largest mangrove forest and biodiversity hotspot', coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'], latitude: 16.8229, longitude: 82.2530, address: 'Coringa, Kakinada District', city: 'Kakinada', state: 'Andhra Pradesh', country: 'India', bestSeason: 'October - May', avgBudget: 1500, difficulty: 'Easy', tags: ['mangroves', 'wildlife', 'birds', 'boat'], categories: ['eco', 'hidden_gem'], featured: false, published: true, avgRating: 4.5, totalReviews: 540, viewCount: 12000, createdAt: '2024-06-19',
  },
  {
    id: 'd21', name: 'Talakona Waterfalls', slug: 'talakona-waterfalls', description: 'With a 270-foot drop, Talakona is the highest waterfall in Andhra Pradesh. Located deep inside Sri Venkateswara National Park, the area is surrounded by dense forests rich in medicinal plants. A fantastic spot for trekking and nature photography.', shortDesc: 'The highest waterfall in Andhra Pradesh nestled in deep forests', coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&h=600&fit=crop'], latitude: 13.8055, longitude: 79.2905, address: 'Sri Venkateswara National Park', city: 'Tirupati', state: 'Andhra Pradesh', country: 'India', bestSeason: 'September - January', avgBudget: 1000, difficulty: 'Moderate', tags: ['waterfalls', 'trekking', 'nature', 'forest'], categories: ['eco', 'adventure', 'hidden_gem'], featured: false, published: true, avgRating: 4.6, totalReviews: 870, viewCount: 16000, createdAt: '2024-06-19',
  },
  {
    id: 'd22', name: 'Horsley Hills', slug: 'horsley-hills', description: 'A picturesque hill station in the Chittoor district offering a cool climate, stunning viewpoints, and ancient eucalyptus trees. Known as the "Ooty of Andhra," it provides a quiet escape from the city heat with activities like zorbing, trekking, and wildlife spotting.', shortDesc: 'The Ooty of Andhra, a serene hill station getaway', coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop'], latitude: 13.6558, longitude: 78.4038, address: 'Horsley Hills, Chittoor District', city: 'Madanapalle', state: 'Andhra Pradesh', country: 'India', bestSeason: 'December - March', avgBudget: 3500, difficulty: 'Easy', tags: ['hill station', 'relax', 'nature', 'views'], categories: ['family', 'eco'], featured: false, published: true, avgRating: 4.4, totalReviews: 1100, viewCount: 22000, createdAt: '2024-06-19',
  },
  {
    id: 'd23', name: 'Yaganti', slug: 'yaganti', description: 'A famous Shiva temple constructed by King Harihara Bukka Raya of the Sangama Dynasty. Renowned for its growing Nandi idol, Pushkarini (holy pond) with continuous water flow, and the Agastya Cave. A blend of profound spirituality and natural caves.', shortDesc: 'Ancient Shiva temple famous for its mysterious growing Nandi idol', coverImage: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&h=600&fit=crop'], latitude: 15.3400, longitude: 78.1400, address: 'Yaganti, Nandyal District', city: 'Kurnool', state: 'Andhra Pradesh', country: 'India', bestSeason: 'October - March', avgBudget: 1200, difficulty: 'Easy', tags: ['temple', 'caves', 'spirituality', 'mystery'], categories: ['religious', 'heritage', 'hidden_gem'], featured: false, published: true, avgRating: 4.8, totalReviews: 760, viewCount: 15000, createdAt: '2024-06-19',
  },
  {
    id: 'd24', name: 'Orvakal Rock Garden', slug: 'orvakal-rock-garden', description: 'A massive park encompassing a 1000-acre area with natural formations of quartz and silica rocks. The surreal rock formations surrounding clear pools of water make it a favorite spot for film shoots and photography enthusiasts.', shortDesc: 'Surreal natural rock formations and quartz deposits', coverImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop'], latitude: 15.7000, longitude: 78.1000, address: 'Orvakal, Kurnool District', city: 'Kurnool', state: 'Andhra Pradesh', country: 'India', bestSeason: 'November - February', avgBudget: 800, difficulty: 'Easy', tags: ['rocks', 'geology', 'photography', 'nature'], categories: ['eco', 'hidden_gem'], featured: false, published: true, avgRating: 4.3, totalReviews: 430, viewCount: 9000, createdAt: '2024-06-19',
  },
  {
    id: 'd25', name: 'Ahobilam', slug: 'ahobilam', description: 'The only place where all nine forms of Lord Narasimha are worshipped. Located amidst the dense Nallamala forest, it combines a profound pilgrimage experience with thrilling trekking routes through rugged hills, dense woods, and streams.', shortDesc: 'Sacred nine temples of Lord Narasimha nestled in dense forests', coverImage: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&h=600&fit=crop'], latitude: 15.1330, longitude: 78.7180, address: 'Ahobilam, Nandyal District', city: 'Kurnool', state: 'Andhra Pradesh', country: 'India', bestSeason: 'September - February', avgBudget: 2500, difficulty: 'Challenging', tags: ['trekking', 'temple', 'forest', 'spirituality'], categories: ['religious', 'adventure', 'hidden_gem'], featured: false, published: true, avgRating: 4.9, totalReviews: 1200, viewCount: 21000, createdAt: '2024-06-19',
  },
  {
    id: 'd26', name: 'Dindi', slug: 'dindi', description: 'A hidden paradise of backwaters in the Godavari delta. Lined with swaying coconut palms, offering serene houseboat cruises, floating resorts, and lush green landscapes. A perfect alternative to the Kerala backwaters.', shortDesc: 'Tranquil backwaters and houseboat cruises in the Godavari delta', coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'], latitude: 16.4389, longitude: 81.8217, address: 'Dindi, Konaseema District', city: 'Razole', state: 'Andhra Pradesh', country: 'India', bestSeason: 'October - March', avgBudget: 5000, difficulty: 'Easy', tags: ['backwaters', 'houseboat', 'nature', 'relax'], categories: ['family', 'eco', 'hidden_gem'], featured: false, published: true, avgRating: 4.6, totalReviews: 890, viewCount: 17000, createdAt: '2024-06-19',
  },
  {
    id: 'd27', name: 'Srisailam', slug: 'srisailam', description: 'Home to one of the 12 Jyotirlingas and a Shakti Peetha, making it a highly revered pilgrimage site. Located in the Nallamala hills on the banks of the Krishna River, it features a massive dam, thrilling ropeways, and the Tiger Reserve.', shortDesc: 'Ancient Jyotirlinga temple surrounded by hills and a majestic dam', coverImage: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&h=600&fit=crop'], latitude: 16.0722, longitude: 78.8689, address: 'Srisailam, Nandyal District', city: 'Srisailam', state: 'Andhra Pradesh', country: 'India', bestSeason: 'September - February', avgBudget: 3500, difficulty: 'Easy', tags: ['temple', 'dam', 'forest', 'wildlife'], categories: ['religious', 'heritage', 'eco'], featured: true, published: true, avgRating: 4.8, totalReviews: 5400, viewCount: 95000, createdAt: '2024-06-19',
  },
  {
    id: 'd28', name: 'Tirupati', slug: 'tirupati', description: 'The spiritual capital of Andhra Pradesh, home to the world-famous Sri Venkateswara Temple on the Tirumala hills. Millions of devotees visit annually. The region also features beautiful waterfalls, ancient forts, and deep spiritual heritage.', shortDesc: 'World-famous pilgrimage destination on the sacred Seven Hills', coverImage: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&h=600&fit=crop'], latitude: 13.6288, longitude: 79.4192, address: 'Tirumala, Tirupati District', city: 'Tirupati', state: 'Andhra Pradesh', country: 'India', bestSeason: 'September - March', avgBudget: 4000, difficulty: 'Easy', tags: ['temple', 'spirituality', 'pilgrimage', 'hills'], categories: ['religious', 'heritage'], featured: true, published: true, avgRating: 4.9, totalReviews: 12500, viewCount: 250000, createdAt: '2024-06-19',
  },
  {
    id: 'd29', name: 'Suryalanka Beach', slug: 'suryalanka-beach', description: 'A pristine, sweeping beach with golden sands and clear waters along the Bay of Bengal. Known for its gentle slope making it perfect for safe swimming. A great coastal getaway avoiding the heavy crowds of major city beaches.', shortDesc: 'Pristine golden sands and safe swimming on the Bay of Bengal', coverImage: '/images/destinations/suryalanka.png', images: ['/images/destinations/suryalanka.png'], latitude: 15.8208, longitude: 80.4578, address: 'Suryalanka, Bapatla District', city: 'Bapatla', state: 'Andhra Pradesh', country: 'India', bestSeason: 'October - March', avgBudget: 2500, difficulty: 'Easy', tags: ['beach', 'relax', 'coastal', 'swimming'], categories: ['family', 'eco', 'hidden_gem'], featured: false, published: true, avgRating: 4.4, totalReviews: 820, viewCount: 16000, createdAt: '2024-06-19',
  },
  {
    id: 'd30', name: 'Pulicat Lake', slug: 'pulicat-lake', description: 'The second largest brackish water lagoon in India, spanning across Andhra Pradesh and Tamil Nadu. The Pulicat Bird Sanctuary is a haven for thousands of migratory birds, most notably the majestic greater flamingos that arrive in winter.', shortDesc: 'Vast lagoon famous for migratory birds and majestic flamingos', coverImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=600&fit=crop'], latitude: 13.6333, longitude: 80.1833, address: 'Pulicat Lake Bird Sanctuary', city: 'Sullurpeta', state: 'Andhra Pradesh', country: 'India', bestSeason: 'November - February', avgBudget: 1500, difficulty: 'Easy', tags: ['birds', 'lagoon', 'flamingos', 'nature'], categories: ['eco', 'hidden_gem'], featured: false, published: true, avgRating: 4.5, totalReviews: 610, viewCount: 14000, createdAt: '2024-06-19',
  },
  {
    id: 'd31', name: 'Ethipothala Waterfalls', slug: 'ethipothala-waterfalls', description: 'A stunning 70-foot high river cascade formed by the combination of three mountain streams. Located near the Nagarjuna Sagar Dam, the falls plunge into a lagoon that houses a crocodile breeding center. Beautifully illuminated in the evenings.', shortDesc: 'Magnificent 70-foot waterfall with a crocodile breeding center', coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&h=600&fit=crop'], latitude: 16.5369, longitude: 79.3130, address: 'Ethipothala, Palnadu District', city: 'Macherla', state: 'Andhra Pradesh', country: 'India', bestSeason: 'August - November', avgBudget: 1000, difficulty: 'Easy', tags: ['waterfalls', 'nature', 'crocodiles', 'scenic'], categories: ['eco', 'family', 'adventure'], featured: false, published: true, avgRating: 4.6, totalReviews: 780, viewCount: 18000, createdAt: '2024-06-19',
  }
];

// ===== EXPERIENCES =====
export const mockExperiences: Experience[] = [
  {
    id: 'e1', guideId: 'g1', guide: mockUsers.find(u => u.id === 'g1')!, destinationId: 'd6', title: 'Old Delhi Food Crawl', slug: 'old-delhi-food-crawl', description: 'Join me on a 4-hour culinary adventure through the narrow lanes of Old Delhi. We\'ll visit 8+ legendary street food stalls, learn about the 400-year history of each dish, and taste flavors you won\'t find in any restaurant.', highlights: ['8+ food stops', 'Historic stories behind each dish', 'Vegetarian & non-veg options', 'Local chai session', 'Spice market visit'], includes: ['All food tastings', 'Bottled water', 'Local guide expertise', 'Food history booklet'], excludes: ['Transportation to meeting point', 'Personal shopping'], coverImage: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=600&fit=crop'], category: 'food', duration: 240, maxGroupSize: 8, pricePerPerson: 1200, languages: ['English', 'Hindi'], difficulty: 'Easy', meetingPoint: 'Jama Masjid Gate No. 1', meetingLat: 28.6507, meetingLng: 77.2334, status: 'published', avgRating: 4.9, totalBookings: 234, featured: true, createdAt: '2024-03-15',
  },
  {
    id: 'e2', guideId: 'g2', guide: mockUsers.find(u => u.id === 'g2')!, destinationId: 'd2', title: 'Western Ghats Eco Trek', slug: 'western-ghats-eco-trek', description: 'A full-day immersive trek through the Western Ghats biodiversity hotspot. Spot endemic bird species, learn about medicinal plants from tribal knowledge, and enjoy a traditional lunch cooked over wood fire at a remote coffee estate.', highlights: ['Endemic bird spotting', 'Medicinal plant identification', 'Waterfall swimming', 'Traditional tribal lunch', 'Coffee plantation tour'], includes: ['Expert guide', 'Traditional lunch', 'Binoculars', 'First aid kit', 'Rain ponchos'], excludes: ['Transport to base camp', 'Camping gear'], coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop'], category: 'eco', duration: 480, maxGroupSize: 6, pricePerPerson: 2500, languages: ['English', 'Kannada', 'Hindi'], difficulty: 'Moderate', meetingPoint: 'Madikeri Bus Stand', meetingLat: 12.4244, meetingLng: 75.7382, status: 'published', avgRating: 4.8, totalBookings: 156, featured: true, createdAt: '2024-04-01',
  },
  {
    id: 'e3', guideId: 'g3', guide: mockUsers.find(u => u.id === 'g3')!, destinationId: 'd1', title: 'Hampi Heritage Bicycle Tour', slug: 'hampi-heritage-bicycle-tour', description: 'Explore the vast Hampi ruins on bicycle — the best way to cover the sprawling UNESCO site. Visit lesser-known temples, underground Shiva temples, ancient water systems, and the Royal Enclosure while I share stories from the Vijayanagara Empire.', highlights: ['Cover 15+ monuments', 'Underground Shiva temple', 'Sunset at Matanga Hill', 'Ancient aqueduct systems', 'Royal Enclosure secrets'], includes: ['Bicycle rental', 'Helmet', 'Water bottles', 'Snacks', 'Entry tickets'], excludes: ['Lunch', 'Camera equipment'], coverImage: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&h=600&fit=crop'], category: 'heritage', duration: 360, maxGroupSize: 8, pricePerPerson: 1800, languages: ['English', 'Hindi', 'Telugu'], difficulty: 'Moderate', meetingPoint: 'Hampi Bazaar', meetingLat: 15.335, meetingLng: 76.46, status: 'published', avgRating: 4.7, totalBookings: 189, featured: true, createdAt: '2024-03-20',
  },
  {
    id: 'e4', guideId: 'g4', guide: mockUsers.find(u => u.id === 'g4')!, title: 'Chennai Filter Coffee & Temple Trail', slug: 'chennai-filter-coffee-temple-trail', description: 'Start your morning with authentic South Indian filter coffee at century-old cafes, visit magnificent Dravidian temples, and end with a traditional banana leaf meal. Experience Chennai like a local!', highlights: ['3 legendary coffee houses', 'Kapaleeshwarar Temple tour', 'Marina Beach sunrise', 'Banana leaf lunch', 'Kolam art demonstration'], includes: ['All food & coffee', 'Temple guide', 'Cultural insights booklet'], excludes: ['Transportation', 'Shopping'], coverImage: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop'], category: 'food', duration: 300, maxGroupSize: 6, pricePerPerson: 1500, languages: ['English', 'Tamil', 'Hindi'], difficulty: 'Easy', meetingPoint: 'Mylapore Tank', meetingLat: 13.0339, meetingLng: 80.2693, status: 'published', avgRating: 4.8, totalBookings: 145, featured: false, createdAt: '2024-04-10',
  },
  {
    id: 'e5', guideId: 'g5', guide: mockUsers.find(u => u.id === 'g5')!, title: 'Goa Beyond Beaches', slug: 'goa-beyond-beaches', description: 'Discover the Goa tourists never see — spice plantations, Portuguese-era churches, hidden waterfalls, local toddy taverns, and traditional Goan village life. This tour takes you away from the party scene into authentic Goa.', highlights: ['Spice plantation tour', 'Hidden waterfall swim', 'Portuguese church visit', 'Traditional Goan lunch', 'Toddy tasting', 'Village pottery workshop'], includes: ['All meals', 'Transport within tour', 'Activity fees', 'Toddy tasting'], excludes: ['Hotel pickup', 'Souvenirs'], coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop', images: ['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop'], category: 'cultural', duration: 420, maxGroupSize: 8, pricePerPerson: 2000, languages: ['English', 'Hindi', 'Konkani'], difficulty: 'Easy', meetingPoint: 'Panaji Church Square', meetingLat: 15.4989, meetingLng: 73.8278, status: 'published', avgRating: 4.6, totalBookings: 98, featured: true, createdAt: '2024-05-01',
  },
  {
    id: 'e6', guideId: 'g1', guide: mockUsers.find(u => u.id === 'g1')!, destinationId: 'd13', title: 'Araku Valley Tribal & Coffee Tour', slug: 'araku-tribal-coffee-tour', description: 'Immerse yourself in the rich tribal culture of Araku Valley. We will visit local tribal villages, witness the traditional Dhimsa dance, and tour expansive coffee plantations to learn how the world-famous Araku Coffee is grown and roasted by indigenous farmers.', highlights: ['Dhimsa tribal dance performance', 'Organic coffee plantation walk', 'Fresh coffee tasting', 'Traditional tribal lunch', 'Visit to Tribal Museum'], includes: ['Museum entry fees', 'Coffee tasting', 'Traditional lunch', 'Guide services'], excludes: ['Transportation to Araku'], coverImage: '/images/araku_valley.png', images: ['/images/araku_valley.png'], category: 'village', duration: 360, maxGroupSize: 10, pricePerPerson: 1800, languages: ['English', 'Telugu', 'Hindi'], difficulty: 'Easy', meetingPoint: 'Araku Railway Station', meetingLat: 18.3273, meetingLng: 82.8775, status: 'published', avgRating: 4.8, totalBookings: 124, featured: true, createdAt: '2024-06-18',
  },
  {
    id: 'e7', guideId: 'g2', guide: mockUsers.find(u => u.id === 'g2')!, destinationId: 'd14', title: 'Borra Caves Spelunking Adventure', slug: 'borra-caves-spelunking', description: 'Explore the depths of the million-year-old Borra Caves. I will guide you through the spectacular stalactite and stalagmite formations, sharing the geological history and local tribal legends associated with these massive limestone structures.', highlights: ['Guided cave exploration', 'Geological history lesson', 'Local myths and legends', 'Photography spots', 'Short hike to Katiki Waterfalls'], includes: ['Cave entry tickets', 'Headlamps', 'Expert guide'], excludes: ['Jeep ride to Katiki waterfalls'], coverImage: '/images/borra_caves.png', images: ['/images/borra_caves.png'], category: 'adventure', duration: 240, maxGroupSize: 15, pricePerPerson: 900, languages: ['English', 'Telugu'], difficulty: 'Moderate', meetingPoint: 'Borra Caves Entrance Gate', meetingLat: 18.2808, meetingLng: 83.0396, status: 'published', avgRating: 4.7, totalBookings: 210, featured: false, createdAt: '2024-06-18',
  }
];

// ===== EVENTS =====
export const mockEvents: TourEvent[] = [
  { id: 'ev1', title: 'Rann Utsav 2025', slug: 'rann-utsav-2025', description: 'The grand festival of the White Desert. Experience folk music, dance, handicraft exhibitions, and the stunning white desert under moonlight. A celebration of Kutch\'s vibrant culture.', coverImage: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=600&fit=crop', images: [], category: 'Cultural Festival', startDate: '2025-11-01', endDate: '2026-02-28', location: 'Dhordo, Kutch', city: 'Kutch', state: 'Gujarat', latitude: 23.7337, longitude: 69.8597, organizer: 'Gujarat Tourism', price: 1500, isFree: false, maxAttendees: 50000, currentAttendees: 32000, tags: ['festival', 'desert', 'cultural', 'music'], featured: true, createdAt: '2024-08-01' },
  { id: 'ev2', title: 'Mysuru Dasara', slug: 'mysuru-dasara-2025', description: 'The royal festival of Mysuru celebrating the victory of good over evil. Witness the grand procession of decorated elephants, palace illumination, and cultural performances spanning 10 days.', coverImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&h=600&fit=crop', images: [], category: 'Religious Festival', startDate: '2025-10-02', endDate: '2025-10-12', location: 'Mysuru Palace, Mysuru', city: 'Mysuru', state: 'Karnataka', latitude: 12.3051, longitude: 76.6551, organizer: 'Mysuru Palace Board', price: 0, isFree: true, maxAttendees: 100000, currentAttendees: 75000, tags: ['festival', 'royal', 'elephants', 'heritage'], featured: true, createdAt: '2024-07-15' },
  { id: 'ev3', title: 'Hornbill Festival', slug: 'hornbill-festival-2025', description: 'The Festival of Festivals celebrating Nagaland\'s tribal heritage. Experience warrior dances, tribal cuisine, traditional sports, music, and the rich tapestry of Naga culture in a stunning Himalayan setting.', coverImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=600&fit=crop', images: [], category: 'Tribal Festival', startDate: '2025-12-01', endDate: '2025-12-10', location: 'Kisama Heritage Village, Kohima', city: 'Kohima', state: 'Nagaland', latitude: 25.6586, longitude: 94.1006, organizer: 'Nagaland Tourism', price: 500, isFree: false, maxAttendees: 20000, currentAttendees: 12000, tags: ['tribal', 'Northeast', 'dance', 'cuisine'], featured: true, createdAt: '2024-09-01' },
  { id: 'ev4', title: 'Jaipur Literature Festival', slug: 'jaipur-lit-fest-2026', description: 'The world\'s largest free literary festival. Hear from global authors, thinkers, and artists in the stunning setting of the Diggi Palace. A celebration of books, ideas, and culture.', coverImage: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&h=600&fit=crop', images: [], category: 'Literary Festival', startDate: '2026-01-22', endDate: '2026-01-26', location: 'Diggi Palace, Jaipur', city: 'Jaipur', state: 'Rajasthan', latitude: 26.9124, longitude: 75.7873, organizer: 'JLF Foundation', price: 0, isFree: true, maxAttendees: 30000, currentAttendees: 18000, tags: ['literature', 'books', 'culture', 'talks'], featured: false, createdAt: '2024-10-01' },
  { id: 'ev5', title: 'Kochi-Muziris Biennale', slug: 'kochi-muziris-biennale-2025', description: 'India\'s largest contemporary art exhibition spanning multiple venues across Fort Kochi. Experience installations, performances, and artworks by artists from around the world in a historic coastal setting.', coverImage: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=600&fit=crop', images: [], category: 'Art Exhibition', startDate: '2025-12-12', endDate: '2026-04-10', location: 'Fort Kochi, Ernakulam', city: 'Kochi', state: 'Kerala', latitude: 9.9658, longitude: 76.2421, organizer: 'Kochi Biennale Foundation', price: 200, isFree: false, maxAttendees: 500000, currentAttendees: 230000, tags: ['art', 'contemporary', 'installations', 'Kerala'], featured: true, createdAt: '2024-09-15' },
];

// ===== REVIEWS =====
export const mockReviews: Review[] = [
  { id: 'r1', authorId: 'u1', author: mockUsers[0], destinationId: 'd1', destination: mockDestinations[0], rating: 5, title: 'Absolutely Magical!', comment: 'Hampi exceeded all my expectations. The boulder-strewn landscape with ancient ruins is unlike anything I\'ve seen. Sunset from Matanga Hill was the highlight of my trip. Definitely hire a local guide — there\'s so much history you\'d miss otherwise.', images: [], helpful: 45, verified: true, createdAt: '2024-11-15' },
  { id: 'r2', authorId: 'u2', author: mockUsers[1], targetUserId: 'g1', rating: 5, title: 'Best Guide in Hyderabad!', comment: 'Arjun made our Hyderabad trip unforgettable. His knowledge of Mughal history is incredible, and he took us to food spots that no tourist would ever find. The biriyani at his secret spot was life-changing! Highly recommend.', images: [], helpful: 32, verified: true, createdAt: '2024-12-01' },
  { id: 'r3', authorId: 'u1', author: mockUsers[0], destinationId: 'd4', destination: mockDestinations[3], rating: 5, title: 'Once in a Lifetime', comment: 'Spiti Valley is raw, remote, and absolutely beautiful. The monastery at Key perched on a cliff is breathtaking. Night skies here are unbelievable — Milky Way visible with naked eyes. Go before it gets too touristy!', images: [], helpful: 67, verified: true, createdAt: '2024-10-20' },
  { id: 'r4', authorId: 'u2', author: mockUsers[1], targetUserId: 'g2', rating: 5, title: 'Incredible Eco Trek', comment: 'Sneha is passionate about conservation and it shows. The Western Ghats trek was well-organized, safe, and educational. She spotted birds I would have completely missed. The tribal lunch was an amazing experience.', images: [], helpful: 28, verified: true, createdAt: '2025-01-10' },
  { id: 'r5', authorId: 'u1', author: mockUsers[0], destinationId: 'd6', destination: mockDestinations[5], rating: 4, title: 'Foodie Paradise', comment: 'Old Delhi food trail is a must-do. The parathas at Parathe Wali Gali were divine. It can get overwhelming with the crowds, so definitely go with a guide who knows the best stalls and can navigate the lanes.', images: [], helpful: 51, verified: true, createdAt: '2025-02-14' },
  { id: 'r6', authorId: 'u2', author: mockUsers[1], destinationId: 'd9', destination: mockDestinations[8], rating: 5, title: 'Nature\'s Engineering Marvel', comment: 'The living root bridges are one of the most incredible things I\'ve seen in my life. The trek down to Nongriat is challenging but absolutely worth it. The double-decker bridge took my breath away. Meghalaya is India\'s best-kept secret!', images: [], helpful: 89, verified: true, createdAt: '2025-03-05' },
];

// ===== SOCIAL POSTS =====
export const mockPosts: Post[] = [
  { id: 'p1', authorId: 'u1', author: mockUsers[0], destinationId: 'd4', destination: mockDestinations[3], content: 'Just came back from Spiti Valley and I\'m still processing how beautiful it was. The Key Monastery at sunrise is something else entirely. If you haven\'t been to Spiti yet, put it on your bucket list NOW! 🏔️✨ #SpitiValley #HiddenIndia #TravelIndia', images: ['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop'], type: 'trip_report', likesCount: 234, commentsCount: 45, sharesCount: 12, isLiked: false, createdAt: '2025-05-20' },
  { id: 'p2', authorId: 'u2', author: mockUsers[1], destinationId: 'd9', destination: mockDestinations[8], content: 'Travel tip: If you\'re visiting the Living Root Bridges in Meghalaya, stay overnight at the village near the double-decker bridge. The morning mist through the roots is pure magic. Also, carry enough water — the trek back up is no joke! 💪🌿', images: ['https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=600&fit=crop'], type: 'tip', likesCount: 189, commentsCount: 32, sharesCount: 24, isLiked: true, createdAt: '2025-05-18' },
  { id: 'p3', authorId: 'g1', author: mockUsers[2], content: 'Excited to announce my new "Hyderabad After Dark" food tour! 🌙🍛 We\'ll explore the legendary late-night biryani spots, chai stalls, and sweet shops that only locals know about. Limited to 6 people per tour for an intimate experience. Book now on TourMate!', images: ['https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=600&fit=crop'], type: 'post', likesCount: 156, commentsCount: 28, sharesCount: 8, isLiked: false, createdAt: '2025-05-15' },
  { id: 'p4', authorId: 'g2', author: mockUsers[3], content: 'Question for fellow eco-tourists: What\'s the most underrated biodiversity hotspot you\'ve visited in India? I\'m planning new trek routes and want to explore beyond the Western Ghats. Drop your suggestions! 🌍🦜', images: [], type: 'question', likesCount: 98, commentsCount: 67, sharesCount: 5, isLiked: false, createdAt: '2025-05-12' },
];

// ===== BADGES =====
export const mockBadges: Badge[] = [
  { id: 'b1', name: 'first_explorer', displayName: 'First Explorer', description: 'Visit your first destination', icon: '🏆', category: 'exploration', difficulty: 'bronze', pointsAwarded: 50, isHidden: false },
  { id: 'b2', name: 'heritage_hunter', displayName: 'Heritage Hunter', description: 'Visit 5 heritage sites', icon: '🏛️', category: 'exploration', difficulty: 'silver', pointsAwarded: 200, isHidden: false },
  { id: 'b3', name: 'hidden_gem_finder', displayName: 'Hidden Gem Finder', description: 'Discover 3 hidden gems', icon: '💎', category: 'exploration', difficulty: 'gold', pointsAwarded: 300, isHidden: false },
  { id: 'b4', name: 'foodie_explorer', displayName: 'Foodie Explorer', description: 'Complete 3 food experiences', icon: '🍛', category: 'exploration', difficulty: 'silver', pointsAwarded: 150, isHidden: false },
  { id: 'b5', name: 'review_champion', displayName: 'Review Champion', description: 'Write 10 helpful reviews', icon: '✍️', category: 'social', difficulty: 'gold', pointsAwarded: 250, isHidden: false },
  { id: 'b6', name: 'social_butterfly', displayName: 'Social Butterfly', description: 'Get 100 likes on your posts', icon: '🦋', category: 'social', difficulty: 'silver', pointsAwarded: 150, isHidden: false },
  { id: 'b7', name: 'week_warrior', displayName: 'Week Warrior', description: '7-day activity streak', icon: '🔥', category: 'streak', difficulty: 'bronze', pointsAwarded: 100, isHidden: false },
  { id: 'b8', name: 'adventure_seeker', displayName: 'Adventure Seeker', description: 'Complete 3 challenging treks', icon: '🏔️', category: 'exploration', difficulty: 'platinum', pointsAwarded: 500, isHidden: false },
  { id: 'b9', name: 'top_guide', displayName: 'Top Guide', description: 'Maintain 4.8+ rating for 50 tours', icon: '⭐', category: 'guide', difficulty: 'platinum', pointsAwarded: 1000, isHidden: false },
  { id: 'b10', name: 'eco_warrior', displayName: 'Eco Warrior', description: 'Visit 5 eco-tourism destinations', icon: '🌿', category: 'exploration', difficulty: 'gold', pointsAwarded: 300, isHidden: false },
];

// ===== MOCK BOOKINGS =====
export const mockBookings: Booking[] = [
  { id: 'bk1', touristId: 'u1', tourist: mockUsers[0], guideId: 'g1', guide: mockUsers[2], destinationId: 'd6', destination: mockDestinations[5], status: 'completed', startDate: '2025-05-10', endDate: '2025-05-10', groupSize: 2, totalAmount: 2400, platformFee: 360, guideEarnings: 2040, specialRequests: 'Vegetarian options preferred', meetingPoint: 'Jama Masjid Gate 1', createdAt: '2025-05-01' },
  { id: 'bk2', touristId: 'u1', tourist: mockUsers[0], guideId: 'g2', guide: mockUsers[3], experienceId: 'e2', experience: mockExperiences[1], status: 'confirmed', startDate: '2025-06-20', endDate: '2025-06-20', groupSize: 3, totalAmount: 7500, platformFee: 1125, guideEarnings: 6375, meetingPoint: 'Madikeri Bus Stand', createdAt: '2025-06-05' },
  { id: 'bk3', touristId: 'u2', tourist: mockUsers[1], guideId: 'g3', guide: mockUsers[4], destinationId: 'd1', destination: mockDestinations[0], status: 'pending', startDate: '2025-07-01', endDate: '2025-07-02', groupSize: 1, totalAmount: 5000, platformFee: 750, guideEarnings: 4250, specialRequests: 'Photography focused tour', createdAt: '2025-06-10' },
  { id: 'bk4', touristId: 'u2', tourist: mockUsers[1], guideId: 'g4', guide: mockUsers[5], experienceId: 'e4', experience: mockExperiences[3], status: 'completed', startDate: '2025-04-15', endDate: '2025-04-15', groupSize: 2, totalAmount: 3000, platformFee: 450, guideEarnings: 2550, createdAt: '2025-04-01' },
];

// ===== MOCK ITINERARY =====
export const mockItineraries: Itinerary[] = [
  {
    id: 'it1', userId: 'u1', title: '3-Day Karnataka Heritage Tour', description: 'An AI-generated heritage trail through Karnataka covering Hampi, Badami, and Coorg', startDate: '2025-07-15', endDate: '2025-07-17', totalBudget: 12000, totalDays: 3, createdAt: '2025-06-01',
    days: [
      { dayNumber: 1, date: '2025-07-15', title: 'Hampi Exploration', estimatedCost: 4000, items: [
        { id: 'i1', time: '06:00', title: 'Sunrise at Matanga Hill', description: 'Trek up for panoramic sunrise views of Hampi ruins', type: 'activity', duration: 90, estimatedCost: 0 },
        { id: 'i2', time: '08:00', title: 'Breakfast at Mango Tree', description: 'Famous riverside restaurant with South Indian breakfast', type: 'food', duration: 60, estimatedCost: 300 },
        { id: 'i3', time: '09:30', title: 'Virupaksha Temple Complex', description: 'Explore the ancient working temple with guide', type: 'destination', duration: 120, estimatedCost: 500, destination: mockDestinations[0] },
        { id: 'i4', time: '12:00', title: 'Lunch & Rest', description: 'Traditional thali at local restaurant', type: 'food', duration: 90, estimatedCost: 400 },
        { id: 'i5', time: '14:00', title: 'Royal Enclosure & Underground Temple', description: 'Visit the King\'s palace, stepped tank, and hidden underground temple', type: 'destination', duration: 180, estimatedCost: 200 },
        { id: 'i6', time: '17:30', title: 'Sunset at Hemakuta Hill', description: 'Watch sunset with views of Virupaksha Temple', type: 'activity', duration: 60, estimatedCost: 0 },
      ]},
      { dayNumber: 2, date: '2025-07-16', title: 'Badami Cave Temples', estimatedCost: 4000, items: [
        { id: 'i7', time: '07:00', title: 'Drive to Badami', description: 'Scenic 4-hour drive from Hampi to Badami', type: 'transport', duration: 240, estimatedCost: 2000 },
        { id: 'i8', time: '12:00', title: 'Badami Cave Temples', description: 'Explore 4 rock-cut cave temples from 6th century', type: 'destination', duration: 180, estimatedCost: 300 },
        { id: 'i9', time: '16:00', title: 'Agastya Lake', description: 'Peaceful lake surrounded by sandstone cliffs', type: 'activity', duration: 60, estimatedCost: 0 },
      ]},
      { dayNumber: 3, date: '2025-07-17', title: 'Coorg Coffee Country', estimatedCost: 4000, items: [
        { id: 'i10', time: '06:00', title: 'Drive to Coorg', description: 'Scenic drive through the ghats', type: 'transport', duration: 300, estimatedCost: 2500 },
        { id: 'i11', time: '12:00', title: 'Coffee Plantation Tour', description: 'Learn about coffee from seed to cup', type: 'activity', duration: 120, estimatedCost: 500, destination: mockDestinations[1] },
        { id: 'i12', time: '15:00', title: 'Abbey Falls', description: 'Visit the scenic waterfall surrounded by coffee and spice plantations', type: 'activity', duration: 90, estimatedCost: 200 },
      ]},
    ],
  },
];

// ===== NOTIFICATIONS =====
export const mockNotifications: Notification[] = [
  { id: 'n1', userId: 'u1', type: 'booking_confirmed', title: 'Booking Confirmed!', body: 'Your eco trek with Sneha has been confirmed for June 20.', read: false, createdAt: '2025-06-05T10:30:00' },
  { id: 'n2', userId: 'u1', type: 'new_recommendation', title: 'New Hidden Gem!', body: 'We found a hidden waterfall near your next destination.', read: false, createdAt: '2025-06-04T14:20:00' },
  { id: 'n3', userId: 'u1', type: 'badge_earned', title: 'Badge Earned! 🏆', body: 'You earned the Heritage Hunter badge!', read: true, createdAt: '2025-06-03T09:15:00' },
  { id: 'n4', userId: 'g1', type: 'new_booking', title: 'New Booking Request', body: 'Rahul wants to book a food crawl on June 25.', read: false, createdAt: '2025-06-06T16:45:00' },
  { id: 'n5', userId: 'g1', type: 'review_received', title: 'New Review ⭐', body: 'Priya left a 5-star review for your heritage walk!', read: true, createdAt: '2025-06-02T11:00:00' },
];

// ===== USER GAMIFICATION =====
export const mockUserPoints: UserPoints = { totalPoints: 1250, currentLevel: 3, levelName: 'Adventurer', nextLevelPoints: 2000, pointsToNextLevel: 750 };
export const mockUserStreak: UserStreak = { currentStreak: 5, longestStreak: 14, lastActivityDate: '2025-06-14' };
export const mockUserBadges: UserBadge[] = [
  { id: 'ub1', userId: 'u1', badge: mockBadges[0], earnedAt: '2024-08-10' },
  { id: 'ub2', userId: 'u1', badge: mockBadges[1], earnedAt: '2025-01-20' },
  { id: 'ub3', userId: 'u1', badge: mockBadges[3], earnedAt: '2025-03-15' },
  { id: 'ub4', userId: 'u1', badge: mockBadges[6], earnedAt: '2025-05-10' },
];

// ===== GUIDE HELPERS =====
export const getGuides = () => mockUsers.filter(u => u.role === 'guide');
export const getTourists = () => mockUsers.filter(u => u.role === 'tourist');
export const getDestinationsByCategory = (cat: string) => mockDestinations.filter(d => d.categories.includes(cat as any));
export const getFeaturedDestinations = () => mockDestinations.filter(d => d.featured);
export const getHiddenGems = () => mockDestinations.filter(d => d.categories.includes('hidden_gem'));
